referall_system/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'))
]

referall_system/user/urls.py
from django.urls import path

from . import views
app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('reg/', views.register_phone, name='registration'),  # ← new entry
    path('verify/', views.verify_code, name='verify'),  # ← new entry
    path('home/', views.home, name='home'),  # ← new entry
]

referall_system/user/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from . import helpers


class AccountManager(BaseUserManager):
    def create_user(self, phone, **extra_fields):
        if not phone:
            raise ValueError("The Email must be set")
        phone = self.normalize_email(phone)
        user = self.model(phone=phone, **extra_fields)
        user.save()
        return user

    def create_superuser(self, phone, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(phone, **extra_fields)


class Account(AbstractBaseUser, PermissionsMixin):
    phone = models.CharField(max_length=50, blank=False, unique=True)
    is_active = False
    referral_code = models.TextField(blank=True, unique=True)

    objects = AccountManager()

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        self.referral_code = helpers.generate_unique(self)
        super(Account, self).save(*args, **kwargs)

    def __str__(self):
        return self.phone


class Referrals(models.Model):
    user_id = models.ForeignKey('Account', on_delete=models.SET_NULL,
                                blank=True, null=True, related_name='referral', default=None)

    referrals = models.OneToOneField('Account', on_delete=models.SET_NULL, blank=True, null=True,
                                     related_name='recommendations', default=None)

referall_system/user/forms.py
from django import forms

from . import models


class UserRegisterForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Phone', 'data-mask': '+0 (000) 000-00-00',
               'style': 'font-size: 13px; text-transform:capitalize'}))


class ReferralCode(forms.Form):
    referral_user = forms.CharField(widget=forms.TextInput(
            attrs={'placeholder': 'Enter Code', 'style': 'font-size: 13px; text-transform:capitalize'}))


class ActivationCodeForm(forms.Form):
    activation_code = forms.CharField(widget=forms.TextInput(
            attrs={'placeholder': 'Enter Code', 'style': 'font-size: 13px; text-transform:capitalize'}))


class ReferralCodeForm(forms.Form):
    referral_code = forms.CharField(widget=forms.TextInput(
            attrs={'placeholder': 'Enter Code', 'style': 'font-size: 13px; text-transform:capitalize'}))

referall_system/user/views.py
import random

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import UserRegisterForm, ActivationCodeForm, ReferralCodeForm
from .models import Account, Referrals


def index(request):
    return render(request, 'index.html')


def register_phone(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            try:
                user = Account.objects.get(phone=form.cleaned_data.get('phone'))
                request.session['pk'] = user.pk
            except:
                request.session['phone'] = form.cleaned_data.get('phone')

            return redirect('user:verify')
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = UserRegisterForm()
        return render(request, 'register.html', {'form': form})


def verify_code(request):
    code = 9214
    if request.method == 'POST':
        form = ActivationCodeForm(request.POST)
        if request.session.get('pk'):
            user = Account.objects.get(pk=request.session.get('pk'))
            if form.is_valid():
                num = form.cleaned_data.get('activation_code')
                if str(code) == str(num):
                    user = authenticate(phone=user.phone)
                    login(request, user)
                    return redirect('user:home')
        else:
            if form.is_valid():
                num = form.cleaned_data.get('activation_code')
                if str(code) == str(num):
                    user = Account.objects.create(phone=request.session['phone'])
                    user = authenticate(phone=user.phone)
                    user.is_active = True
                    login(request, user)
                    return redirect('user:home')

        return render(request, 'confirm_code.html', {'form': form})
    else:
        form = ActivationCodeForm()
        return render(request, 'confirm_code.html', {'form': form})


@login_required
def home(request):
    user = request.user
    recommendations = user.referral.all()
    try:
        referral = Referrals.objects.get(referrals=user)
        return render(request, 'home.html', {'rec': recommendations, 'referral': referral})
    except Referrals.DoesNotExist:
        pass

    if request.method == 'POST':
        code_form = ReferralCodeForm(request.POST)

        if code_form.is_valid():
            if not code_form.cleaned_data.get('referral_code') == user.referral_code:
                try:
                    user_ = Account.objects.get(referral_code=code_form.cleaned_data.get('referral_code'))
                    Referrals.objects.create(user_id=user_, referrals=user)
                    return redirect('user:home')
                except Account.DoesNotExist:
                    pass
    else:
        code_form = ReferralCodeForm()
        return render(request, 'home.html', {'form': code_form, 'rec': recommendations})

    return render(request, 'home.html', {'form': code_form, 'rec': recommendations})

referall_system/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Referral system</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
        integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </body>
</html>

referall_system/templates/confirm_code.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}



{% block content %}
 <div class="container  mt-5 mb-5" style="max-width: 95%">
     <div class="d-flex flex-column">
         <h1>Confirm login</h1>
         <form method="POST" enctype="multipart/form-data" class="mt-3 " autocomplete="off">
             {% csrf_token %}
             <div class="row">
                    <div class="col-4"> {{ form.activation_code|as_crispy_field }} </div>
             </div>
            <button type="submit" class="btn btn-primary btn-sm mt-3" style="width: 90px;">Confirm</button>
         </form>
     </div>
 </div>
{% endblock %}

referall_system/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}

<span>User: {{request.user.phone}}</span>
<span style="margin-left: 50px;">Your code: {{ request.user.referral_code }}</span>
<br>
{% if referral %}
<span>User who invite you: {{referral.user_id}}</span>
{% else %}
<form method="POST" enctype="multipart/form-data" class="mt-3 " autocomplete="off">
    {% csrf_token %}
    <div class="row">
        <div class="col-4"> {{ form.referral_code | as_crispy_field }}</div>
    </div>
    <button type="submit" class="btn btn-primary btn-sm mt-3" style="width: 90px;">Confirm</button>
</form>
{% endif %}
<br>
<ul>
    {% for inv in rec %}
    <li>Users who invited by you: {{inv.referrals}}</li>
    {% endfor %}
</ul>

{% endblock %}

referall_system/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Referral system django demo</h1>
  <p>Hello!</p>
<a href="{% url  'user:registration' %}" class="btn btn-primary btn-sm mt-3" style="width: 90px;">Register</a>

{% endblock %}

referall_system/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}



{% block content %}
 <div class="container  mt-5 mb-5" style="max-width: 95%">
     <div class="d-flex flex-column">
         <h1>Register/Login</h1>
         <form method="POST" enctype="multipart/form-data" class="mt-3 " autocomplete="off">
             {% csrf_token %}
             <div class="row">
                    <div class="col-4"> {{ form.phone|as_crispy_field }} </div>
             </div>
            <button type="submit" class="btn btn-primary btn-sm mt-3" style="width: 90px;">Register</button>
         </form>
     </div>
 </div>
{% endblock %}